version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: database
    env_file:
      - .env
    ports:
      -"5432:5432"
    networks:
      - app-network
    volumes:
      -pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecommerce-app
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    network:
      - app-network
      
networks:
  app-network

volumes:
  pgdata: